all: program64-static program64-dynamic program32-static

program64-static: program.c dockcross-x64
	./dockcross-x64 bash -c '$$CC program.c -o program64-static -static'

program64-dynamic: program.c dockcross-x64
	./dockcross-x64 bash -c '$$CC program.c -o program64-dynamic'

program32-static: program.c dockcross-x86
	./dockcross-x86 bash -c '$$CC program.c -o program32-static -static'

dockcross-x64:
	docker run --rm dockcross/linux-x64 > ./dockcross-x64
	chmod +x ./dockcross-x64

dockcross-x86:
	docker run --rm dockcross/linux-x86 > ./dockcross-x86
	chmod +x ./dockcross-x86

clean:
	rm -f dockcross-* program64-static program64-dynamic program32-static
